# embed_shader.cmake — convert a compiled fxc .cso into a C++ header holding
# the byte array, so shaders ship inside the exe (M14 package = exe + system
# DLLs only; no runtime file lookups).
#
# Usage: cmake -DINPUT=<file.cso> -DOUTPUT=<file.h> -DNAME=<arrayName> -P embed_shader.cmake

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED NAME)
    message(FATAL_ERROR "INPUT, OUTPUT and NAME are required")
endif()

file(READ "${INPUT}" _hex HEX)
# "abcd12..." -> "0xab, 0xcd, 0x12, ..."
string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1," _hex "${_hex}")
string(REGEX REPLACE ",$" "" _hex "${_hex}")

file(WRITE "${OUTPUT}"
"// Generated by cmake/embed_shader.cmake from ${INPUT} — do not edit.\n"
"#pragma once\n"
"#include <cstddef>\n"
"namespace vw::gfx {\n"
"inline constexpr unsigned char ${NAME}[] = { ${_hex} };\n"
"inline constexpr std::size_t ${NAME}_size = sizeof(${NAME});\n"
"} // namespace vw::gfx\n")
